### ISSUE TITLE
Review project status

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/boringssl#108]
In checking all OQS subproject statuses we've also come across this project: It doesn't seem overly active (e.g., actively following the upstream master), so we wonder whether this should somehow be reflected in the README. @pi-314159 any suggestions in this regard?

**Comment by pi-314159** [comment]
I agree. Here is the current plan

- Updated boringssl every 2-3 months; I’ll bring X25519 hybrid algorithms to boringssl in the next update
- Build a new Chromium when liboqs has a new release

**Comment by pi-314159** [comment]
I agree. Here is the current plan

- Update boringssl every 2-3 months; I’ll bring X25519 hybrid algorithms to boringssl in the next update
- Build a new Chromium when liboqs has a new release

**Comment by baentsch** [comment]
> Build a new Chromium when liboqs has a new release

There's been [a liboqs release](https://github.com/open-quantum-safe/liboqs/releases/tag/0.9.2), so where do we put a new Chromium build (and for which platforms)?

**Comment by pi-314159** [comment]
Yes I noticed that. We're on the spring festival holiday now; we will build one in early March.
