### ISSUE TITLE
Failed setting curve list

### ISSUE THREAD

**Issue by yogitagolhani** [open-quantum-safe/boringssl#15]
On writing a code "tool/bssl client -curves <KEX> -connect localhost:4433", i am getting error 
**Failed setting curves list**

I have tried with these syntaxes:
1. tool/bssl client -curves oqs_kemdefault -connect localhost:4433
2.tool/bssl client -curves frodo640aes -connect localhost:4433
3.tool/bssl client -curves p256_frodo640aes -connect localhost:4433

Also, I am trying to do the setup by installing docker on top of windows10 operating system and inside docker , i have installed ubuntu and then trying to do the setu of boringssl to start with chromim demo

**Comment by xvzcf** [comment]
I'm not able to reproduce this on my Ubuntu 19.10 machine. What sequence of build steps did you run?

**Comment by yogitagolhani** [comment]
Thanks for the reply. The structure of my setup is :
1.Windows10 Operating System ->Docker linux container -> Installed ubunto image on it with the configuration 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
2. ran all the steps till cmake -DBUILD_SHARED_LIBRARIES=ON -GNinja ... as mentioned in the link "https://github.com/open-quantum-safe/boringssl#linux"
3. Got into error on the step **ninja run_tests** Attachmnt contains the error we encountered .
[error_BoringSSL (1).txt](https://github.com/open-quantum-safe/boringssl/files/4598764/error_BoringSSL.1.txt)

Note: I had chceked the file  CMakeLists.txt and it is same  what wee trying to build.

**Comment by xvzcf** [comment]
The attached file suggests that you ran the command in `/Boring/liboqs/build`, which I assume is the build directory for liboqs and not for BoringSSL. You have to execute `ninja run_{basic|full}_oqs_tests` in the build directory for BoringSSL, which I presume would be `/Boring/build`

**Comment by yogitagolhani** [comment]
Thanks for the lead , I am able to build the code and TLS handshake worked :). You can close the issue
