### ISSUE TITLE
Boringssl Test on lsquic

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#34]
Hello, I found a quic implementation in C that uses boringssl for the transport layer. I thought swapping the SSL layer with oqs-boringssl will allow for post-quantum certs to work. I am not sure if there is an issue with my certificate generation but I get this error when I try to establish a connection with post-quantum certificates.
 SSL_CTX_use_PrivateKey_file failed

**Comment by xvzcf** [comment]
How were the certificates generated? Can you provide a Dockerfile that replicates this issue?

**Comment by prchander** [comment]
Yes. I will start generating the docker file. Should the container contain the openssl key and certificate generation, and the lsquic implementation?

**Comment by xvzcf** [comment]
Sure, that would be helpful.

**Comment by prchander** [comment]
Sorry for the late response but are there any good documentation to create a docker container from a VM?

**Comment by prchander** [comment]
I uploaded the files to Google Drive but here are the links for the tar files. One link is for the server and the other is for the client.
server - https://drive.google.com/file/d/1ATOWSfk-bNy3YoA46clQQtmpmZ-FdC2z/view?usp=sharing
client - https://drive.google.com/file/d/1bXEl5Dw3UpFOGDs56lMzU8YUjHdlNYMj/view?usp=sharing

**Comment by xvzcf** [comment]
Hi @prchander, sorry for the delay in getting back to you, but would it at all be possible to upload the image on Docker Hub?

**Comment by prchander** [comment]
This problem has been solved. Thank you for the help
