### ISSUE TITLE
boringssl private key error with lsquic

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#38]
Hello, I had a question in my previous issue as I was requested to upload a Docker image for the error produced while using the lsquic and boringssl implementations. I have the tar files ready but they are too high to upload on GitHub (1.87 Gb for server and client). Is there any other way that I can upload the containers?

**Comment by prchander** [comment]
I uploaded the files to Google Drive but here are the links for the tar files. One link is for the server and the other is for the client. 
server - https://drive.google.com/file/d/1ATOWSfk-bNy3YoA46clQQtmpmZ-FdC2z/view?usp=sharing
client - https://drive.google.com/file/d/1bXEl5Dw3UpFOGDs56lMzU8YUjHdlNYMj/view?usp=sharing

**Comment by dstebila** [comment]
See @34.
