### ISSUE TITLE
Boringssl install cannot find libssl.so 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#51]
Hello, I have tried a docker container and a new vm and I am facing issues installing liboqs then boringssl. 
-- Build files have been written to: /home/pi/oqs/boringssl/build
[393/447] Linking CXX shared library ssl/libssl.so
FAILED: ssl/libssl.so

Steps I used to install 
it clone --branch master https://github.com/open-quantum-safe/boringssl.git

BORINGSSL_DIR=$PWD/boringssl

#Build liboqs
#------------

git clone https://github.com/open-quantum-safe/liboqs.git
cd liboqs

rm -rf build
mkdir build && cd build

cmake -G"Ninja" -DCMAKE_INSTALL_PREFIX=$BORINGSSL_DIR/oqs -DOQS_USE_OPENSSL=OFF ..

ninja
sudo ninja install

#Build OQS BoringSSL
#-------------------

cd $BORINGSSL_DIR
rm -rf build
mkdir build && cd build

cmake -DBUILD_SHARED_LIBS=ON -GNinja ..

ninja

**Comment by baentsch** [comment]
Can you show the output error message, please? I'm not the boringssl expert but why would `libssl` be needed at all if you build without it (-DOQS_USE_OPENSSL=OFF)? In addition, if you build `boringssl` shared, should you not build `liboqs` also shared?
