### ISSUE TITLE
BoringSSL client certificate verification 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#58]
Hello, I have performed a couple of server client connections with rsa 3072 and falcon1024 with the following code:
Server : {bssl_dir} server -cert rsa_crt.pem -key rsa_srv.pem -accept 44330 
client : echo "X" | {bssl_dir} client -connect 10.0.0.157:44330 -root-certs rsa_CA.pem

Server : {bssl_dir} server -cert falcon1024_crt.pem -key falcon1024_srv.pem -accept 44330 
client : echo "X" | {bssl_dir} client -connect 10.0.0.157:44330 -root-certs falcon1024_CA.pem

With rsa, the client is able to verify the server with CA certificate but with the post quantum algorithms, it fails with the following error : 

error on client side:
Connecting to 10.0.0.157:44330
Error while connecting: UNKNOWN_SIGNATURE_ALGORITHM
94279995259064:error:0c0000b8:ASN.1 encoding routines:OPENSSL_internal:UNKNOWN_SIGNATURE_ALGORITHM:../crypto/x509/algorithm.c:184:
94279995259064:error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:../ssl/handshake.cc:361:
0.008458852767944336

error on server side:
Error while connecting: TLSV1_ALERT_DECRYPT_ERROR
94331224088968:error:1000041b:SSL routines:OPENSSL_internal:TLSV1_ALERT_DECRYPT_ERROR:../ssl/tls_record.cc:592:SSL alert number 51

Is it using the non post quantum openssl libraries and if so how do I fix this?

**Comment by xvzcf** [comment]
@prchander can you check if [this branch](https://github.com/open-quantum-safe/boringssl/tree/cert-fixes) fixes the problem?

**Comment by prchander** [comment]
@xvzcf thank you for your help. I recompiled the library with the new branch. I did the test with dilithium2 and got new errors that I have not seen before. 
Server side: 
Error while connecting: TLSV1_ALERT_DECRYPT_ERROR
94310030606728:error:1000041b:SSL routines:OPENSSL_internal:TLSV1_ALERT_DECRYPT_ERROR:../ssl/tls_record.cc:592:SSL alert number 51
Client side:
Error while connecting: INVALID_SIGNATURE
94493787453192:error:06000083:public key routines:OPENSSL_internal:INVALID_SIGNATURE:../crypto/evp/p_oqs.c:102:
94493787453192:error:0b000006:X.509 certificate routines:OPENSSL_internal:public key routines:../crypto/x509/a_verify.c:104:
94493787453192:error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:../ssl/handshake.cc:361:

**Comment by xvzcf** [comment]
I can't seem to reproduce this. Does it work with Falcon? Are both OpenSSL and BoringSSL built against the same liboqs commit?

**Comment by prchander** [comment]
@xvzcf I apologize for the confusion. I recompiled everything again and everything works now.
Thank you for your help

**Comment by xvzcf** [comment]
Reopening until the branch gets merged in.

**Comment by xvzcf** [comment]
Fixed by https://github.com/open-quantum-safe/boringssl/pull/59
