### ISSUE TITLE
Interoperability testing with OpenSSL

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/boringssl#6]

**Comment by dstebila** [comment]
As part of interoperability testing, need to check signature interoperability, specifically which hash algorithm is used, as BoringSSL may fix the signature algorithm to SHA-256 but OpenSSL may use different SHA-2 variants for different security levels.

**Comment by xvzcf** [comment]
Closed by https://github.com/open-quantum-safe/openssl/pull/198
