### ISSUE TITLE
Hybrid certificate verification 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#61]
Hello, this topic was discussed in issue #58 which functions for the the post-quantum certificates but the NID's for the hybrids are still not added.

**Comment by xvzcf** [comment]
We currently do not support hybrid signatures in BoringSSL, nor do we plan to anytime soon. It might be worth revisiting at some point.

**Comment by prchander** [comment]
I appreciate your response and help with #58. This is just a question is there a reason why boringssl is not supporting hybrids at this time?

**Comment by xvzcf** [comment]
I guess there's no reason in particular, just that we haven't had the time to look into it.

**Comment by xvzcf** [comment]
Re-opening this since it hasn't been implemented yet, and can serve as additional documentation in the meanwhile.

**Comment by baentsch** [comment]
> Re-opening this since it hasn't been implemented yet, and can serve as additional documentation in the meanwhile.

What about labelling this as "future work" as we probably won't do this anytime soon, right? In addition/alternatively, what about adding an explicit statement to the README signature section stating that hybrids are not supported? That way it's clear and we don't need to keep this issue just for documentation purposes.

**Comment by xvzcf** [comment]
Both sound good.
