### ISSUE TITLE
Connection terminate after handshake

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#67]
Is there an option in BoringSSL to terminate the connection after handshake? Currently after the connection, there is an active connection and the only way to stop it is with a ctrl+c. So, I am just wondering if there is another option.

**Comment by baentsch** [comment]
This seems to be no OQS-specific question but rather one that should be placed upstream. Personally, I'm also not sure about the benefit of this feature: Why should an application terminate a connection after handshake? The purpose of TLS is to send data over the connection once the handshake completes... Do you want this for testing? Are you referencing an OpenSSL feature?

**Comment by xvzcf** [comment]
> Is there an option in BoringSSL to terminate the connection after handshake? Currently after the connection, there is an active connection and the only way to stop it is with a ctrl+c. So, I am just wondering if there is another option.

I don't think there's a flag in `bssl client` that lets you do this, but in our OpenSSL-BoringSSL interop tests, we use a [shim binary](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-interop-test/test_basic.py#L43) that provides a `shim-shuts-down` flag.

The default behaviour of `bssl server` is to terminate once the client has closed the connection.
