### ISSUE TITLE
Session-out not writing to file 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/boringssl#73]
Hello, I have a basic client and server that I was testing session resumption on.  The client had this code:
~/oqs/boringssl/build/tool/bssl client -connect 10.0.0.2:44330 -session-out res.txt

The connection established but it does not write anything to the file. Am I doing something wrong with the file format?

**Comment by xvzcf** [comment]
Can you try:

- Starting the server with:

```
./tool/bssl server -accept 44330 -www
```

- And then starting the client with:

```
echo 'GET /' | ./tool/bssl client -connect 10.0.0.2:44330 -session-out res.txt
```

**Comment by mraavi5** [comment]
It's working with that set of commands. Thank you!!
